# Generated by Django 5.1.6 on 2025-08-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msinventoryapp', '0002_seed_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
