# Generated by Django 5.1.6 on 2025-08-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msinventoryapp', '0003_alter_product_barcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internal_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
